export const movies = [
  {
    id: 148,
    title: "The General",
    year: 1926,
    rating: 8.1,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYmRiMDFlYjYtOTMwYy00OGY2LWE0Y2QtYzQxOGNhZmUwNTIxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "When Union spies steal an engineer's beloved locomotive, he pursues it single-handedly and straight through enemy lines.",
    director: "Clyde Bruckman, Buster Keaton",
    cast: ["Buster Keaton", "Marion Mack", "Glen Cavender", "Jim Farley"]
  },
  {
    id: 149,
    title: "Jurassic Park",
    year: 1993,
    rating: 8.2,
    genre: "Adventure",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX300.jpg",
    summary: "A pragmatic paleontologist touring an almost complete theme park on an island is tasked with protecting a couple of kids after a power failure causes cloned dinosaurs to run loose.",
    director: "Steven Spielberg",
    cast: ["Sam Neill", "Laura Dern", "Jeff Goldblum", "Richard Attenborough"]
  },
  {
    id: 150,
    title: "Sherlock Jr.",
    year: 1924,
    rating: 8.2,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZWFhOGU5NDctY2Q3YS00Y2VlLWI1NzEtZmIwY2ZiZjY4OTA2XkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg",
    summary: "A film projectionist longs to be a detective, and puts his meagre skills to work when he is framed by a rival for stealing his girlfriend's watch.",
    director: "Buster Keaton",
    cast: ["Buster Keaton", "Kathryn McGuire", "Joe Keaton", "Erwin Connelly"]
  },
  {
    id: 151,
    title: "Warrior",
    year: 2011,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTk4ODk5MTMyNV5BMl5BanBnXkFtZTcwMDMyNTg0Ng@@._V1_SX300.jpg",
    summary: "The youngest son of an alcoholic former boxer returns home, where he's trained by his father for competition in a mixed martial arts tournament.",
    director: "Gavin O'Connor",
    cast: ["Tom Hardy", "Nick Nolte", "Joel Edgerton", "Jennifer Morrison"]
  },
  {
    id: 152,
    title: "The Grand Budapest Hotel",
    year: 2014,
    rating: 8.1,
    genre: "Adventure",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg",
    summary: "A writer encounters the owner of an aging high-class hotel who tells him of his early years serving as a lobby boy in the hotel's glorious years.",
    director: "Wes Anderson",
    cast: ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric", "Adrien Brody"]
  },
  {
    id: 153,
    title: "The Kid",
    year: 1921,
    rating: 8.3,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZjhhMThhNDItNTY2MC00MmU1LTliNDEtNDdhZjdlNTY5ZDQ1XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
    summary: "The Tramp cares for an abandoned child, but events put their relationship in jeopardy.",
    director: "Charlie Chaplin",
    cast: ["Charlie Chaplin", "Edna Purviance", "Jackie Coogan", "Carl Miller"]
  },
  {
    id: 154,
    title: "Prisoners",
    year: 2013,
    rating: 8.1,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTg0NTIzMjQ1NV5BMl5BanBnXkFtZTcwNDc3MzM5OQ@@._V1_SX300.jpg",
    summary: "When Keller Dover's daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads.",
    director: "Denis Villeneuve",
    cast: ["Hugh Jackman", "Jake Gyllenhaal", "Viola Davis", "Maria Bello"]
  },
  {
    id: 155,
    title: "Harry Potter and the Deathly Hallows: Part 2",
    year: 2011,
    rating: 8.1,
    genre: "Fantasy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    summary: "Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.",
    director: "David Yates",
    cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Ralph Fiennes"]
  },
  {
    id: 156,
    title: "The Treasure of the Sierra Madre",
    year: 1948,
    rating: 8.2,
    genre: "Adventure",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOTJlZWMxYzEtMjlkNC00MTQ5LWJkODktNTEwNTkxODI2NTRlXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg",
    summary: "Two Americans searching for work in Mexico convince an old prospector to help them mine for gold in the Sierra Madre Mountains.",
    director: "John Huston",
    cast: ["Humphrey Bogart", "Walter Huston", "Tim Holt", "Bruce Bennett"]
  },
  {
    id: 157,
    title: "Dial M for Murder",
    year: 1954,
    rating: 8.2,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOWIwODIxYWItZDI4MS00YzhhLWE3MmYtMzlhZDIwOTMzZmE5L2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
    summary: "A former tennis player tries to arrange his wife's murder after learning of her affair.",
    director: "Alfred Hitchcock",
    cast: ["Ray Milland", "Grace Kelly", "Robert Cummings", "John Williams"]
  },
  {
    id: 158,
    title: "Fargo",
    year: 1996,
    rating: 8.1,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNDJiZDgyZjctYmRjMS00ZjdkLTkwMTEtNGU1NDg3NDQ0Yzk1XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "Minnesota car salesman Jerry Lundegaard's inept crime falls apart due to his and his henchmen's bungling and the persistent police work of pregnant officer Marge Gunderson.",
    director: "Joel Coen, Ethan Coen",
    cast: ["William H. Macy", "Frances McDormand", "Steve Buscemi", "Peter Stormare"]
  },
  {
    id: 159,
    title: "Andhadhun",
    year: 2018,
    rating: 8.2,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYzhiY2Y2YTEtZjYxNi00ZDRlLTk3NDUtMGQxNGE3OTgxYjZmXkEyXkFqcGdeQXVyMTMxMjA5MjU1._V1_SX300.jpg",
    summary: "A series of mysterious events change the life of a blind pianist who now must report a crime that was actually never witnessed by him.",
    director: "Sriram Raghavan",
    cast: ["Ayushmann Khurrana", "Tabu", "Radhika Apte", "Anil Dhawan"]
  },
  {
    id: 160,
    title: "Trainspotting",
    year: 1996,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMzA5Zjc3ZTMtMmU5YS00YTMwLWI4MWUtYTU0YTVmNjVmODZhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out, despite the allure of the drugs and influence of friends.",
    director: "Danny Boyle",
    cast: ["Ewan McGregor", "Ewen Bremner", "Jonny Lee Miller", "Kevin McKidd"]
  },
  {
    id: 161,
    title: "Million Dollar Baby",
    year: 2004,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTkxNzA1NDQxOV5BMl5BanBnXkFtZTcwNTkyMTIzMw@@._V1_SX300.jpg",
    summary: "A determined woman works with a hardened boxing trainer to become a professional.",
    director: "Clint Eastwood",
    cast: ["Hilary Swank", "Clint Eastwood", "Morgan Freeman", "Jay Baruchel"]
  },
  {
    id: 162,
    title: "The Elephant Man",
    year: 1980,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMDVjNjIwOGItNDE3Ny00OThjLWE0NzQtZTU3YjMzZTZjMzhkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    summary: "A Victorian surgeon rescues a heavily disfigured man who is mistreated while scraping a living as a side-show freak.",
    director: "David Lynch",
    cast: ["Anthony Hopkins", "John Hurt", "Anne Bancroft", "John Gielgud"]
  },
  {
    id: 163,
    title: "Arrival",
    year: 2016,
    rating: 7.9,
    genre: "Sci-Fi",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTExMzU0ODcxNDheQTJeQWpwZ15BbWU4MDE1OTI4MzAy._V1_SX300.jpg",
    summary: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
    director: "Denis Villeneuve",
    cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker", "Michael Stuhlbarg"]
  },
  {
    id: 164,
    title: "Incendies",
    year: 2010,
    rating: 8.3,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMWE3MGYzZjktY2Q5Mi00Y2NiLWIyYWUtMmIyNzA3YmZlMGFhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    summary: "Twins journey to the Middle East to discover their family history and fulfill their mother's last wishes.",
    director: "Denis Villeneuve",
    cast: ["Lubna Azabal", "Mélissa Désormeaux-Poulin", "Maxim Gaudette", "Mustafa Kamel"]
  },
  {
    id: 165,
    title: "The Battle of Algiers",
    year: 1966,
    rating: 8.1,
    genre: "War",
    poster_url: "https://m.media-amazon.com/images/M/MV5BN2M5YTQyNzEtMGUyYi00ZmU5LWJjZDgtMTQ1Zjg2MWQ1YTc2XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    summary: "In the 1950s, fear and violence escalate as the people of Algiers fight for independence from the French government.",
    director: "Gillo Pontecorvo",
    cast: ["Brahim Hadjadj", "Jean Martin", "Yacef Saadi", "Samia Kerbash"]
  },
  {
    id: 166,
    title: "Wild Strawberries",
    year: 1957,
    rating: 8.2,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYTdlMmU3YjctMzNiOS00N2FiLWI2MDgtYjJkYzY0ZGM0NTU0XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    summary: "After living a life marked by coldness, an aging professor is forced to confront the emptiness of his existence.",
    director: "Ingmar Bergman",
    cast: ["Victor Sjöström", "Bibi Andersson", "Ingrid Thulin", "Gunnar Björnstrand"]
  },
  {
    id: 167,
    title: "The Third Man",
    year: 1949,
    rating: 8.1,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYjE2OTdhMWUtOGJlMy00ZDViLWIzZjgtYjZkZGZmMDZjYmEyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend.",
    director: "Carol Reed",
    cast: ["Orson Welles", "Joseph Cotten", "Alida Valli", "Trevor Howard"]
  },
  {
    id: 168,
    title: "Groundhog Day",
    year: 1993,
    rating: 8.0,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZWIxNzM5YzQtY2FmMS00Yjc3LWI1ZjUtNGVjMjMzZTIxZTIxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "A weatherman finds himself inexplicably living the same day over and over again.",
    director: "Harold Ramis",
    cast: ["Bill Murray", "Andie MacDowell", "Chris Elliott", "Stephen Tobolowsky"]
  },
  {
    id: 169,
    title: "To Kill a Mockingbird",
    year: 1962,
    rating: 8.3,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNmVmYzcyMWMtMzRjZC00ZWEzLWFiZTAtMDcyNDY2MjNlOWJiXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "Atticus Finch, a widowed lawyer in Depression-era Alabama, defends a black man against an undeserved rape charge, and teaches his children about morality.",
    director: "Robert Mulligan",
    cast: ["Gregory Peck", "John Megna", "Frank Overton", "Rosemary Murphy"]
  },
  {
    id: 170,
    title: "The Gold Rush",
    year: 1925,
    rating: 8.2,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZjEyOTE4MzMtNmMzMy00Mzc3LWJlOTQtOGJiNDE0ZmJiOTU4L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    summary: "A prospector goes to the Klondike during the 1890s gold rush in hopes of making his fortune, and is smitten with a girl he sees in a dance hall.",
    director: "Charlie Chaplin",
    cast: ["Charlie Chaplin", "Mack Swain", "Tom Murray", "Henry Bergman"]
  },
  {
    id: 171,
    title: "On the Waterfront",
    year: 1954,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BY2I0MWFiZDMtNWQyYy00Njk5LTk3MDktZjZjNTNmZGJkNTJhXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
    summary: "An ex-prize fighter turned New Jersey longshoreman struggles to stand up to his corrupt union bosses, including his older brother.",
    director: "Elia Kazan",
    cast: ["Marlon Brando", "Karl Malden", "Lee J. Cobb", "Rod Steiger"]
  },
  {
    id: 172,
    title: "Mr. Smith Goes to Washington",
    year: 1939,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZTYwYjYxYzgtMDE1Ni00NzU4LWJlMTEtODQ5YmJmMGJhZjI5L2ltYWdlXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg",
    summary: "A naive youth leader is appointed to fill a vacancy in the U.S. Senate and soon confronts corruption and deception in Washington.",
    director: "Frank Capra",
    cast: ["James Stewart", "Jean Arthur", "Claude Rains", "Edward Arnold"]
  },
  {
    id: 173,
    title: "Rebecca",
    year: 1940,
    rating: 8.1,
    genre: "Mystery",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYTcxYWExOTMtMWFmYy00ZTdmLWE4OGItMDFmZTdkNmVlY2JkXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
    summary: "A self-conscious woman juggles adjusting to her new role as an aristocrat's wife and avoiding being intimidated by his first wife's spectral presence.",
    director: "Alfred Hitchcock",
    cast: ["Laurence Olivier", "Joan Fontaine", "George Sanders", "Judith Anderson"]
  },
  {
    id: 174,
    title: "Yojimbo",
    year: 1961,
    rating: 8.2,
    genre: "Action",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZThiZjAzZjgtNDU3MC00YThhLThjYWUtZGRkYjc2ZWZlOTVjXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
    summary: "A crafty ronin comes to a town divided by two criminal gangs and decides to play them against each other to free the town.",
    director: "Akira Kurosawa",
    cast: ["Toshirô Mifune", "Eijirô Tôno", "Tatsuya Nakadai", "Yôko Tsukasa"]
  },
  {
    id: 175,
    title: "The Notebook",
    year: 2004,
    rating: 7.8,
    genre: "Romance",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTk3OTM5Njg5M15BMl5BanBnXkFtZTYwMzA0ODI3._V1_SX300.jpg",
    summary: "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are soon separated by social differences.",
    director: "Nick Cassavetes",
    cast: ["Gena Rowlands", "James Garner", "Rachel McAdams", "Ryan Gosling"]
  },
  {
    id: 176,
    title: "Drishyam",
    year: 2015,
    rating: 8.2,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTcwNzkxNjI4OF5BMl5BanBnXkFtZTgwMDc5NTk2NjE@._V1_SX300.jpg",
    summary: "A man goes to extreme lengths to save his family from punishment after the family commits an accidental crime.",
    director: "Nishikant Kamat",
    cast: ["Ajay Devgn", "Shriya Saran", "Tabu", "Rajat Kapoor"]
  },
  {
    id: 177,
    title: "Before Sunset",
    year: 2004,
    rating: 8.1,
    genre: "Romance",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTQ1MjAwNTM5Ml5BMl5BanBnXkFtZTYwNDM0MTc3._V1_SX300.jpg",
    summary: "Nine years after Jesse and Celine first met, they encounter each other again on the French leg of Jesse's book tour.",
    director: "Richard Linklater",
    cast: ["Ethan Hawke", "Julie Delpy", "Vernon Dobtcheff", "Louise Lemoine Torrès"]
  },
  {
    id: 178,
    title: "Les Diaboliques",
    year: 1955,
    rating: 8.1,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BODU5MDQyODItYzU5Yi00YzkxLWEwYmYtNzExMjU2YTQzZTgxXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
    summary: "The wife and mistress of a loathed school principal plan to murder him with what they believe to be the perfect alibi.",
    director: "Henri-Georges Clouzot",
    cast: ["Simone Signoret", "Véra Clouzot", "Paul Meurisse", "Charles Vanel"]
  },
  {
    id: 179,
    title: "Howl's Moving Castle",
    year: 2004,
    rating: 8.2,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNmM4YTFmMmItMGE3Yy00MmRkLTlmZGEtMzZlOTQzYjk3MzA2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    summary: "When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent wizard.",
    director: "Hayao Miyazaki",
    cast: ["Chieko Baishô", "Takuya Kimura", "Tatsuya Gashûin", "Akihiro Miwa"]
  },
  {
    id: 180,
    title: "Cinema Paradiso",
    year: 1988,
    rating: 8.5,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BM2FhYjEyYmYtMDI1Yy00YTdlLWI2NWQtYmEzNzAxOGY1NjY2XkEyXkFqcGdeQXVyNTA3NTIyNDg@._V1_SX300.jpg",
    summary: "A filmmaker recalls his childhood when falling in love with the pictures at the cinema of his home village and forms a deep friendship with the projectionist.",
    director: "Giuseppe Tornatore",
    cast: ["Philippe Noiret", "Enzo Cannavale", "Antonella Attili", "Isa Danieli"]
  },
  {
    id: 181,
    title: "Stand by Me",
    year: 1986,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BODJmY2Y2OGQtMDg2My00N2Q3LWJmZTUtYTc2ODBjZDVlNDlhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    summary: "After the death of one of his friends, a writer recounts a childhood journey with his friends to find the body of a missing boy.",
    director: "Rob Reiner",
    cast: ["Wil Wheaton", "River Phoenix", "Corey Feldman", "Jerry O'Connell"]
  },
  {
    id: 182,
    title: "The Deer Hunter",
    year: 1978,
    rating: 8.1,
    genre: "War",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNDhmNTA0ZDMtYjhkNS00NzEzLWIzYTItOGNkMTVmYjE2YmI3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "An in-depth examination of the ways in which the Vietnam War impacts and disrupts the lives of several friends in a small steel mill town in Pennsylvania.",
    director: "Michael Cimino",
    cast: ["Robert De Niro", "Christopher Walken", "John Cazale", "John Savage"]
  },
  {
    id: 183,
    title: "The Wages of Fear",
    year: 1953,
    rating: 8.1,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZDdkNzMwZmUtY2Q5MS00ZmM2LTg0Y2ItMzRhZjhhNGM2ODA0L2ltYWdlXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
    summary: "In a decrepit South American village, four men are hired to transport an urgent nitroglycerine shipment without the equipment that would make it safe.",
    director: "Henri-Georges Clouzot",
    cast: ["Yves Montand", "Charles Vanel", "Peter van Eyck", "Folco Lulli"]
  },
  {
    id: 1,
    title: "The Shawshank Redemption",
    year: 1994,
    rating: 9.3,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNDg4NjM1YjMtYmNhZC00MjM0LWFiZmYtNGY1YjA3MzZmODc5XkEyXkFqcGdeQXVyNDk5ODk0OTU@._V1_SX300.jpg",
    summary: "Amélie is an innocent and naive girl in Paris with her own sense of justice who decides to help those around her and discover love.",
    director: "Jean-Pierre Jeunet",
    cast: ["Audrey Tautou", "Mathieu Kassovitz", "Rufus", "Lorella Cravotta"]
  },
  {
    id: 74,
    title: "Full Metal Jacket",
    year: 1987,
    rating: 8.3,
    genre: "War",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNzkxODk0NjEtYjc4Mi00ZDI0LTgyYjEtYzc1NDkxY2YzYTgyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits.",
    director: "Stanley Kubrick",
    cast: ["Matthew Modine", "R. Lee Ermey", "Vincent D'Onofrio", "Adam Baldwin"]
  },
  {
    id: 75,
    title: "Bicycle Thieves",
    year: 1948,
    rating: 8.3,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNzNiM2I0ZjEtZTBjNi00ZmY0LWE1YzctYjJjZDI0YTc0NGViXkEyXkFqcGdeQXVyMTc4MzI2NQ@@._V1_SX300.jpg",
    summary: "In post-war Italy, a working-class man's bicycle is stolen, endangering his efforts to find work.",
    director: "Vittorio De Sica",
    cast: ["Lamberto Maggiorani", "Enzo Staiola", "Lianella Carell", "Elena Altieri"]
  },
  {
    id: 76,
    title: "Singin' in the Rain",
    year: 1952,
    rating: 8.3,
    genre: "Musical",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZDRjNGViMjQtOThlMi00MTA3LThkYzQtNzJmMGJkMGRiYTUyXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg",
    summary: "A silent film star falls for a chorus girl just as he and his delusionally jealous screen partner are trying to make the transition to talkies.",
    director: "Stanley Donen, Gene Kelly",
    cast: ["Gene Kelly", "Donald O'Connor", "Debbie Reynolds", "Jean Hagen"]
  },
  {
    id: 77,
    title: "Snatch",
    year: 2000,
    rating: 8.3,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTA2NDYxOGYtYjU1Mi00Y2QzLTgxMTQtMWI1MGI0ZGQ5MmU4XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
    summary: "Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers, and bent cops clash.",
    director: "Guy Ritchie",
    cast: ["Jason Statham", "Brad Pitt", "Benicio Del Toro", "Dennis Farina"]
  },
  {
    id: 78,
    title: "Toy Story 3",
    year: 2010,
    rating: 8.3,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
    summary: "The toys are mistakenly delivered to a day-care center instead of the attic before Andy leaves for college, and they try to escape.",
    director: "Lee Unkrich",
    cast: ["Tom Hanks", "Tim Allen", "Joan Cusack", "Ned Beatty"]
  },
  {
    id: 79,
    title: "Inglourious Basterds",
    year: 2009,
    rating: 8.3,
    genre: "War",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
    summary: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner.",
    director: "Quentin Tarantino",
    cast: ["Brad Pitt", "Diane Kruger", "Eli Roth", "Mélanie Laurent"]
  },
  {
    id: 80,
    title: "L.A. Confidential",
    year: 1997,
    rating: 8.2,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMDQ2YzEyZGItYWRhOS00MjBmLTkzMDUtMTdjYzkyMmQxZTJlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "As corruption grows in 1950s Los Angeles, three policemen investigate a series of murders with their own brand of justice.",
    director: "Curtis Hanson",
    cast: ["Kevin Spacey", "Russell Crowe", "Guy Pearce", "Kim Basinger"]
  },
  {
    id: 81,
    title: "Scarface",
    year: 1983,
    rating: 8.3,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNjdjNGQ4NDEtNTEwYS00MTgxLTliYzQtYzE2ZDRiZjFhZmNlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "In 1980 Miami, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.",
    director: "Brian De Palma",
    cast: ["Al Pacino", "Michelle Pfeiffer", "Steven Bauer", "Mary Elizabeth Mastrantonio"]
  },
  {
    id: 82,
    title: "Metropolis",
    year: 1927,
    rating: 8.3,
    genre: "Sci-Fi",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTg2Mjk5ODg2OV5BMl5BanBnXkFtZTgwODA0NzY3NjE@._V1_SX300.jpg",
    summary: "In a futuristic city sharply divided between the working class and the city planners, the son of the city's mastermind falls in love with a prophet.",
    director: "Fritz Lang",
    cast: ["Brigitte Helm", "Alfred Abel", "Gustav Fröhlich", "Rudolf Klein-Rogge"]
  },
  {
    id: 83,
    title: "Die Hard",
    year: 1988,
    rating: 8.2,
    genre: "Action",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZjRlNDUxZjAtOGQ4OC00OTNlLTgxNmQtYTBmMDgwZmNmNjkxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party at Nakatomi Plaza.",
    director: "John McTiernan",
    cast: ["Bruce Willis", "Alan Rickman", "Bonnie Bedelia", "Reginald VelJohnson"]
  },
  {
    id: 84,
    title: "Rashomon",
    year: 1950,
    rating: 8.2,
    genre: "Mystery",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjEzMzA4NDE2MF5BMl5BanBnXkFtZTcwNTc5MDI2NQ@@._V1_SX300.jpg",
    summary: "The rape of a bride and the murder of her samurai husband are recalled from the perspectives of four witnesses.",
    director: "Akira Kurosawa",
    cast: ["Toshirô Mifune", "Machiko Kyô", "Masayuki Mori", "Takashi Shimura"]
  },
  {
    id: 85,
    title: "The Green Mile",
    year: 1999,
    rating: 8.6,
    genre: "Fantasy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg",
    summary: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder who has a mysterious gift.",
    director: "Frank Darabont",
    cast: ["Tom Hanks", "Michael Clarke Duncan", "David Morse", "Bonnie Hunt"]
  },
  {
    id: 86,
    title: "Harakiri",
    year: 1962,
    rating: 8.2,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYjBmYTQ1NjItZWU5MS00YjI0LTg2OTYtYmFkN2JkMmNiNWVkXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_SX300.jpg",
    summary: "When a ronin requesting to commit ritual suicide is told of another samurai who thought he could make money with the gesture.",
    director: "Masaki Kobayashi",
    cast: ["Tatsuya Nakadai", "Akira Ishihama", "Shima Iwashita", "Tetsurô Tanba"]
  },
  {
    id: 87,
    title: "The Apartment",
    year: 1960,
    rating: 8.2,
    genre: "Romance",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNzkwODFjNzItMmMwNi00MTU5LWE2MzktM2M4ZDczZGM1MmViXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg",
    summary: "A Manhattan insurance clerk tries to rise in his company by letting its executives use his apartment for trysts, but complications arise.",
    director: "Billy Wilder",
    cast: ["Jack Lemmon", "Shirley MacLaine", "Fred MacMurray", "Ray Walston"]
  },
  {
    id: 88,
    title: "Indiana Jones and the Last Crusade",
    year: 1989,
    rating: 8.2,
    genre: "Adventure",
    poster_url: "https://m.media-amazon.com/images/M/MV5BY2Q0ODg4ZmItNDZiYi00ZWY5LTg2NzctNmYwZjA5OThmNzE1XkEyXkFqcGdeQXVyMjM4MzQ4OTQ@._V1_SX300.jpg",
    summary: "In 1938, after his father goes missing while pursuing the Holy Grail, Indiana Jones finds himself up against the Nazis again.",
    director: "Steven Spielberg",
    cast: ["Harrison Ford", "Sean Connery", "Alison Doody", "Denholm Elliott"]
  },
  {
    id: 89,
    title: "Good Will Hunting",
    year: 1997,
    rating: 8.3,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOTI0MzcxMTYtZDVkMy00NjY1LTgyMTYtZmUxN2M3NmQ2NWJhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    summary: "Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.",
    director: "Gus Van Sant",
    cast: ["Robin Williams", "Matt Damon", "Ben Affleck", "Stellan Skarsgård"]
  },
  {
    id: 90,
    title: "Unforgiven",
    year: 1992,
    rating: 8.2,
    genre: "Western",
    poster_url: "https://m.media-amazon.com/images/M/MV5BODM3YWY4NmQtN2Y3Ni00OTg0LWFhZGQtZWE3ZWY4MTJlOWU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "Retired Old West gunslinger William Munny reluctantly takes on one last job with the help of his old partner and a young man.",
    director: "Clint Eastwood",
    cast: ["Clint Eastwood", "Gene Hackman", "Morgan Freeman", "Richard Harris"]
  },
  {
    id: 91,
    title: "Raging Bull",
    year: 1980,
    rating: 8.2,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYjRmODkzNDItMTNhNi00YjJlLTg0ZjAtODlhZTM0YzgzYThlXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SX300.jpg",
    summary: "The life of boxer Jake LaMotta, whose violence and temper led him to the top but threatened to destroy his professional career and family.",
    director: "Martin Scorsese",
    cast: ["Robert De Niro", "Cathy Moriarty", "Joe Pesci", "Frank Vincent"]
  },
  {
    id: 92,
    title: "Ran",
    year: 1985,
    rating: 8.2,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMmU1NGYwZWYtOWExNi00ZTEyLTgwMmMtNGE5YzViZWFjYjZhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    summary: "In Medieval Japan, an elderly warlord retires, handing over his empire to his three sons, but soon they begin to fight for power.",
    director: "Akira Kurosawa",
    cast: ["Tatsuya Nakadai", "Akira Terao", "Jinpachi Nezu", "Daisuke Ryû"]
  },
  {
    id: 93,
    title: "A Clockwork Orange",
    year: 1971,
    rating: 8.3,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTY3MjM1Mzc4N15BMl5BanBnXkFtZTgwODM0NzAxMDE@._V1_SX300.jpg",
    summary: "In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesn't go as planned.",
    director: "Stanley Kubrick",
    cast: ["Malcolm McDowell", "Patrick Magee", "Michael Bates", "Warren Clarke"]
  },
  {
    id: 94,
    title: "The Sting",
    year: 1973,
    rating: 8.3,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNGU3NjQ4YTMtZGJjOS00YTQ3LThmNmItMTI5MDE2ODI3NjdlXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    summary: "Two grifters team up to pull off the ultimate con on a crime boss.",
    director: "George Roy Hill",
    cast: ["Paul Newman", "Robert Redford", "Robert Shaw", "Charles Durning"]
  },
  {
    id: 95,
    title: "Jaws",
    year: 1975,
    rating: 8.1,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    summary: "When a killer shark unleashes chaos on a beach community off Cape Cod, a local sheriff teams up with a marine biologist and an old seafarer.",
    director: "Steven Spielberg",
    cast: ["Roy Scheider", "Robert Shaw", "Richard Dreyfuss", "Lorraine Gary"]
  },
  {
    id: 96,
    title: "The Sixth Sense",
    year: 1999,
    rating: 8.2,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMWM4NTFhYjctNzUyNi00NGMwLTk3NTYtMDIyNTZmMzRlYmQyXkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_SX300.jpg",
    summary: "A boy who communicates with spirits seeks the help of a disheartened child psychologist.",
    director: "M. Night Shyamalan",
    cast: ["Bruce Willis", "Haley Joel Osment", "Toni Collette", "Olivia Williams"]
  },
  {
    id: 97,
    title: "Spider-Man: No Way Home",
    year: 2021,
    rating: 8.2,
    genre: "Action",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg",
    summary: "With Spider-Man's identity revealed, Peter asks Doctor Strange for help, but when a spell goes wrong, dangerous foes from other worlds start to appear.",
    director: "Jon Watts",
    cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Jacob Batalon"]
  },
  {
    id: 98,
    title: "The Big Lebowski",
    year: 1998,
    rating: 8.1,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTQ0NjUzMDMyOF5BMl5BanBnXkFtZTgwODA1OTU0MDE@._V1_SX300.jpg",
    summary: "Jeff 'The Dude' Lebowski, mistaken for a millionaire of the same name, seeks restitution for his ruined rug and enlists his bowling buddies to help.",
    director: "Joel Coen, Ethan Coen",
    cast: ["Jeff Bridges", "John Goodman", "Julianne Moore", "Steve Buscemi"]
  },
  {
    id: 99,
    title: "No Country for Old Men",
    year: 2007,
    rating: 8.2,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg",
    summary: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
    director: "Joel Coen, Ethan Coen",
    cast: ["Tommy Lee Jones", "Javier Bardem", "Josh Brolin", "Woody Harrelson"]
  },
  {
    id: 100,
    title: "The Thing",
    year: 1982,
    rating: 8.2,
    genre: "Horror",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNGViZWZmM2EtNGYzZi00ZDAyLTk3ODMtNzIyZTBjN2Y1NmM1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    summary: "A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.",
    director: "John Carpenter",
    cast: ["Kurt Russell", "Wilford Brimley", "Keith David", "Richard Masur"]
  },
  {
    id: 101,
    title: "Monty Python and the Holy Grail",
    year: 1975,
    rating: 8.2,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BN2IyNTE4YzUtZWU0Mi00MGIwLTgyMmQtMzQ4YzQxYWNlYWE2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "King Arthur and his Knights of the Round Table embark on a surreal, low-budget search for the Holy Grail.",
    director: "Terry Gilliam, Terry Jones",
    cast: ["Graham Chapman", "John Cleese", "Eric Idle", "Terry Gilliam"]
  },
  {
    id: 102,
    title: "Ikiru",
    year: 1952,
    rating: 8.3,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTQ5Mzg5NjM2NV5BMl5BanBnXkFtZTgwOTM4NjM3MTE@._V1_SX300.jpg",
    summary: "A bureaucrat tries to find meaning in his life after he discovers he has terminal cancer.",
    director: "Akira Kurosawa",
    cast: ["Takashi Shimura", "Nobuo Kaneko", "Shin'ichi Himori", "Haruo Tanaka"]
  },
  {
    id: 103,
    title: "Kill Bill: Vol. 1",
    year: 2003,
    rating: 8.2,
    genre: "Action",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNzM3NDFhYTAtYmU5Mi00NGRmLTljYjgtMDkyODQ4MjNkMGY2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.",
    director: "Quentin Tarantino",
    cast: ["Uma Thurman", "David Carradine", "Daryl Hannah", "Michael Madsen"]
  },
  {
    id: 104,
    title: "Star Wars",
    year: 1977,
    rating: 8.6,
    genre: "Sci-Fi",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",
    summary: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station.",
    director: "George Lucas",
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Alec Guinness"]
  },
  {
    id: 105,
    title: "Up",
    year: 2009,
    rating: 8.3,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX300.jpg",
    summary: "78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.",
    director: "Pete Docter, Bob Peterson",
    cast: ["Edward Asner", "Jordan Nagai", "John Ratzenberger", "Christopher Plummer"]
  },
  {
    id: 106,
    title: "Heat",
    year: 1995,
    rating: 8.3,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYjZjNTJlZGUtZTE3Ny00Y2RkLTg0ZjEtY2JlYzI5ZjczN2VmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a clue at their latest heist.",
    director: "Michael Mann",
    cast: ["Al Pacino", "Robert De Niro", "Val Kilmer", "Jon Voight"]
  },
  {
    id: 107,
    title: "Hotel Rwanda",
    year: 2004,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZGJjYmIzZmQtNWE4Yy00ZGVmLWJkZGEtMzUzNmQ4ZWFlMjRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    summary: "Paul Rusesabagina, a hotel manager, houses over a thousand Tutsi refugees during their struggle against the Hutu militia in Rwanda.",
    director: "Terry George",
    cast: ["Don Cheadle", "Sophie Okonedo", "Joaquin Phoenix", "Xolani Mali"]
  },
  {
    id: 108,
    title: "Life Is Beautiful",
    year: 1997,
    rating: 8.6,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTJiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    summary: "When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will and humor to protect his son.",
    director: "Roberto Benigni",
    cast: ["Roberto Benigni", "Nicoletta Braschi", "Giorgio Cantarini", "Giustino Durano"]
  },
  {
    id: 109,
    title: "Logan",
    year: 2017,
    rating: 8.1,
    genre: "Action",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYzc5MTU4N2EtYTkyMi00NjdhLTg3NWEtMTY4OTEyMzJhZTAzXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
    summary: "In a near future, a weary Logan cares for an ailing Professor X while protecting a young mutant girl from dark forces.",
    director: "James Mangold",
    cast: ["Hugh Jackman", "Patrick Stewart", "Dafne Keen", "Boyd Holbrook"]
  },
  {
    id: 110,
    title: "The Prestige",
    year: 2006,
    rating: 8.5,
    genre: "Mystery",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg",
    summary: "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything.",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Hugh Jackman", "Scarlett Johansson", "Michael Caine"]
  },
  {
    id: 111,
    title: "Monsters, Inc.",
    year: 2001,
    rating: 8.1,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTY1NTI0ODUyOF5BMl5BanBnXkFtZTgwNTEyNjQ0MDE@._V1_SX300.jpg",
    summary: "In order to power the city, monsters have to scare children; however, they are terribly afraid themselves of being contaminated by children.",
    director: "Pete Docter, David Silverman, Lee Unkrich",
    cast: ["Billy Crystal", "John Goodman", "Mary Gibbs", "Steve Buscemi"]
  },
  {
    id: 112,
    title: "Before Sunrise",
    year: 1995,
    rating: 8.1,
    genre: "Romance",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZDdiZTAwYzAtMDI3Ni00OTRjLTkzN2UtMGE3MDMyZmU4NTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "A young man and woman meet on a train in Europe and wind up spending one evening together in Vienna, forming a connection before they part ways.",
    director: "Richard Linklater",
    cast: ["Ethan Hawke", "Julie Delpy", "Andrea Eckert", "Hanno Pöschl"]
  },
  {
    id: 113,
    title: "Casino",
    year: 1995,
    rating: 8.2,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTcxOWYzNDYtYmM4YS00N2NkLTk0NTAtNjg1ODgwZjAxYzI3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
    summary: "A tale of greed, deception, money, power, and murder occur between two best friends and a casino owner over a gambling empire.",
    director: "Martin Scorsese",
    cast: ["Robert De Niro", "Sharon Stone", "Joe Pesci", "James Woods"]
  },
  {
    id: 114,
    title: "The Grand Budapest Hotel",
    year: 2014,
    rating: 8.1,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg",
    summary: "A writer encounters the owner of an aging high-class hotel who tells him of his early years serving as a lobby boy.",
    director: "Wes Anderson",
    cast: ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric", "Adrien Brody"]
  },
  {
    id: 115,
    title: "Shutter Island",
    year: 2010,
    rating: 8.2,
    genre: "Mystery",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYzhiNDkyNzktNTZmYS00ZTBkLTk2MDAtM2U0YjU1MzgxZjgzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    summary: "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.",
    director: "Martin Scorsese",
    cast: ["Leonardo DiCaprio", "Emily Mortimer", "Mark Ruffalo", "Ben Kingsley"]
  },
  {
    id: 116,
    title: "Platoon",
    year: 1986,
    rating: 8.1,
    genre: "War",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMzRjZjdlMjQtODVkYS00N2YzLWJlYWYtMGVlN2E5MWEwMWQzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    summary: "A young soldier in Vietnam faces a moral crisis when confronted with the horrors of war and the duality of man.",
    director: "Oliver Stone",
    cast: ["Charlie Sheen", "Tom Berenger", "Willem Dafoe", "Forest Whitaker"]
  },
  {
    id: 117,
    title: "Pan's Labyrinth",
    year: 2006,
    rating: 8.2,
    genre: "Fantasy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    summary: "In the Falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
    director: "Guillermo del Toro",
    cast: ["Ivana Baquero", "Ariadna Gil", "Sergi López", "Maribel Verdú"]
  },
  {
    id: 118,
    title: "Dune",
    year: 2021,
    rating: 8.0,
    genre: "Sci-Fi",
    poster_url: "https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    summary: "Paul Atreides arrives on Arrakis after his father accepts stewardship of the dangerous planet, the only source of the most valuable substance.",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Rebecca Ferguson", "Zendaya", "Oscar Isaac"]
  },
  {
    id: 119,
    title: "There Will Be Blood",
    year: 2007,
    rating: 8.2,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjAxODQ4MDU5NV5BMl5BanBnXkFtZTcwMDU4MjU1MQ@@._V1_SX300.jpg",
    summary: "A story of family, greed, religion, and oil, centered around a turn-of-the-century prospector in the early days of the oil business.",
    director: "Paul Thomas Anderson",
    cast: ["Daniel Day-Lewis", "Paul Dano", "Ciarán Hinds", "Kevin J. O'Connor"]
  },
  {
    id: 120,
    title: "The Wolf of Wall Street",
    year: 2013,
    rating: 8.2,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg",
    summary: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime and corruption.",
    director: "Martin Scorsese",
    cast: ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie", "Matthew McConaughey"]
  },
  {
    id: 121,
    title: "Inside Out",
    year: 2015,
    rating: 8.1,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg",
    summary: "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions conflict on how best to navigate a new city and school.",
    director: "Pete Docter, Ronnie Del Carmen",
    cast: ["Amy Poehler", "Phyllis Smith", "Richard Kind", "Bill Hader"]
  },
  {
    id: 122,
    title: "Finding Nemo",
    year: 2003,
    rating: 8.2,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZjMxYzBiNjUtZDliNC00MDAyLTg1NWUtY2RjY2VhN2UzNWE2XkEyXkFqcGdeQXVyNjE2MjQwNjc@._V1_SX300.jpg",
    summary: "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
    director: "Andrew Stanton, Lee Unkrich",
    cast: ["Albert Brooks", "Ellen DeGeneres", "Alexander Gould", "Willem Dafoe"]
  },
  {
    id: 123,
    title: "V for Vendetta",
    year: 2005,
    rating: 8.2,
    genre: "Action",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOTI5ODc3NzExNV5BMl5BanBnXkFtZTcwNzYxNzQzMw@@._V1_SX300.jpg",
    summary: "In a future British dystopian society, a shadowy freedom fighter plots to overthrow the government with the help of a young woman.",
    director: "James McTeigue",
    cast: ["Hugo Weaving", "Natalie Portman", "Rupert Graves", "Stephen Rea"]
  },
  {
    id: 124,
    title: "The Secret in Their Eyes",
    year: 2009,
    rating: 8.2,
    genre: "Mystery",
    poster_url: "https://m.media-amazon.com/images/M/MV5BY2FhZGI5M2QtZWFiZS00NzY4LTgwODItNzFlNGJkNGJjYjljXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    summary: "A retired legal counselor writes a novel hoping to find closure for one of his past unresolved homicide cases and for his unreciprocated love.",
    director: "Juan José Campanella",
    cast: ["Ricardo Darín", "Soledad Villamil", "Pablo Rago", "Carla Quevedo"]
  },
  {
    id: 125,
    title: "Ratatouille",
    year: 2007,
    rating: 8.1,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTMzODU0NTkxMF5BMl5BanBnXkFtZTcwMjQ4MzMzMw@@._V1_SX300.jpg",
    summary: "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.",
    director: "Brad Bird, Jan Pinkava",
    cast: ["Brad Garrett", "Lou Romano", "Patton Oswalt", "Ian Holm"]
  },
  {
    id: 126,
    title: "Black Swan",
    year: 2010,
    rating: 8.0,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX300.jpg",
    summary: "A committed dancer struggles to maintain her sanity after winning the lead role in a production of Tchaikovsky's Swan Lake.",
    director: "Darren Aronofsky",
    cast: ["Natalie Portman", "Mila Kunis", "Vincent Cassel", "Winona Ryder"]
  },
  {
    id: 127,
    title: "The Intouchables",
    year: 2011,
    rating: 8.5,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_SX300.jpg",
    summary: "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.",
    director: "Olivier Nakache, Éric Toledano",
    cast: ["François Cluzet", "Omar Sy", "Anne Le Ny", "Audrey Fleurot"]
  },
  {
    id: 128,
    title: "How to Train Your Dragon",
    year: 2010,
    rating: 8.1,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_SX300.jpg",
    summary: "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, changing both their worlds.",
    director: "Dean DeBlois, Chris Sanders",
    cast: ["Jay Baruchel", "Gerard Butler", "Christopher Mintz-Plasse", "Craig Ferguson"]
  },
  {
    id: 129,
    title: "My Neighbor Totoro",
    year: 1988,
    rating: 8.1,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYzJjMTYyMjQtZDI0My00ZjE2LTkyNGYtOTllNGQxNDMyZjE0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    summary: "When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.",
    director: "Hayao Miyazaki",
    cast: ["Hitoshi Takagi", "Noriko Hidaka", "Chika Sakamoto", "Shigesato Itoi"]
  },
  {
    id: 130,
    title: "Blade Runner",
    year: 1982,
    rating: 8.1,
    genre: "Sci-Fi",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.",
    director: "Ridley Scott",
    cast: ["Harrison Ford", "Rutger Hauer", "Sean Young", "Edward James Olmos"]
  },
  {
    id: 131,
    title: "The Seventh Seal",
    year: 1957,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjQ4NjMzNzc4NV5BMl5BanBnXkFtZTgwMTg1ODA5NjE@._V1_SX300.jpg",
    summary: "A man seeks answers about life, death, and the existence of God as he plays chess against the Grim Reaper during the Black Plague.",
    director: "Ingmar Bergman",
    cast: ["Max von Sydow", "Gunnar Björnstrand", "Bengt Ekerot", "Nils Poppe"]
  },
  {
    id: 132,
    title: "Klaus",
    year: 2019,
    rating: 8.2,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMWYwOThjM2ItZGYxNy00NTQwLWFlZWEtM2MzM2Q5MmY3NDU5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    summary: "A simple act of kindness always sparks another, even in a frozen, faraway place. When Jesper distinguishes himself as the postal academy's worst student.",
    director: "Sergio Pablos, Carlos Martínez López",
    cast: ["Jason Schwartzman", "J.K. Simmons", "Rashida Jones", "Will Sasso"]
  },
  {
    id: 133,
    title: "Taxi Driver",
    year: 1976,
    rating: 8.2,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BM2M1MmVhNDgtNmI0YS00ZDNmLTkyNjctNTJiYTQ2N2NmYzc2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence feeds his urge for violent action.",
    director: "Martin Scorsese",
    cast: ["Robert De Niro", "Jodie Foster", "Cybill Shepherd", "Albert Brooks"]
  },
  {
    id: 134,
    title: "Mad Max: Fury Road",
    year: 2015,
    rating: 8.1,
    genre: "Action",
    poster_url: "https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    summary: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the help of a group of female prisoners.",
    director: "George Miller",
    cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult", "Hugh Keays-Byrne"]
  },
  {
    id: 135,
    title: "The Truman Show",
    year: 1998,
    rating: 8.2,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMDIzODcyY2EtMmY2MC00ZWVlLTgwMzAtMjQwOWUyNmJjNTYyXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
    summary: "An insurance salesman discovers his whole life is actually a reality TV show.",
    director: "Peter Weir",
    cast: ["Jim Carrey", "Ed Harris", "Laura Linney", "Noah Emmerich"]
  },
  {
    id: 136,
    title: "Gone Girl",
    year: 2014,
    rating: 8.1,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTk0MDQ3MzAzOV5BMl5BanBnXkFtZTgwNzU1NzE3MjE@._V1_SX300.jpg",
    summary: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him.",
    director: "David Fincher",
    cast: ["Ben Affleck", "Rosamund Pike", "Neil Patrick Harris", "Tyler Perry"]
  },
  {
    id: 137,
    title: "The Bridge on the River Kwai",
    year: 1957,
    rating: 8.1,
    genre: "War",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOGY5NmNlMmQtYzRlYy00NGQ5LWJkZTYtYWJhMTcxZTc4MDQxXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg",
    summary: "British POWs are forced to build a railway bridge across the river Kwai for their Japanese captors, unaware that the Allies are planning to destroy it.",
    director: "David Lean",
    cast: ["William Holden", "Alec Guinness", "Jack Hawkins", "Sessue Hayakawa"]
  },
  {
    id: 138,
    title: "Room",
    year: 2015,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjE4NzgzNzEwMl5BMl5BanBnXkFtZTgwMTMzMDE0NjE@._V1_SX300.jpg",
    summary: "Held captive for years in an enclosed space, a woman and her young son finally gain their freedom, allowing them to experience the outside world.",
    director: "Lenny Abrahamson",
    cast: ["Brie Larson", "Jacob Tremblay", "Sean Bridgers", "Wendy Crewson"]
  },
  {
    id: 139,
    title: "Rush",
    year: 2013,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOWEwODJmZDItYTNmZC00OGM4LThlNDktOTQzZjIzMGQxODA4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "The merciless 1970s rivalry between Formula One rivals James Hunt and Niki Lauda.",
    director: "Ron Howard",
    cast: ["Daniel Brühl", "Chris Hemsworth", "Olivia Wilde", "Alexandra Maria Lara"]
  },
  {
    id: 140,
    title: "Hacksaw Ridge",
    year: 2016,
    rating: 8.1,
    genre: "War",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjQ1NjM3MTUxNV5BMl5BanBnXkFtZTgwMDc5MTY5OTE@._V1_SX300.jpg",
    summary: "World War II American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first Conscientious Objector.",
    director: "Mel Gibson",
    cast: ["Andrew Garfield", "Sam Worthington", "Luke Bracey", "Teresa Palmer"]
  },
  {
    id: 141,
    title: "Gran Torino",
    year: 2008,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTc5NTk2OTU1Nl5BMl5BanBnXkFtZTcwMDc3NjAwMg@@._V1_SX300.jpg",
    summary: "Disgruntled Korean War veteran Walt Kowalski sets out to reform his neighbor, Thao Lor, who tried to steal his prized car.",
    director: "Clint Eastwood",
    cast: ["Clint Eastwood", "Bee Vang", "Christopher Carley", "Ahney Her"]
  },
  {
    id: 142,
    title: "Mary and Max",
    year: 2009,
    rating: 8.1,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMDgzYjQwMDMtNGUzYi00MTRmLWIyMGMtNjE1OGZkNzY2YWIzL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "A tale of friendship between two unlikely pen pals: Mary, a lonely eight-year-old girl living in the suburbs, and Max, a forty-four-year old man.",
    director: "Adam Elliot",
    cast: ["Toni Collette", "Philip Seymour Hoffman", "Barry Humphries", "Eric Bana"]
  },
  {
    id: 143,
    title: "Ford v Ferrari",
    year: 2019,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BM2UwMDVmMDItM2I2Yi00NGZmLTk4ZTUtY2JjNTQ3OGQ5ZjM2XkEyXkFqcGdeQXVyMTA1OTYzOTUx._V1_SX300.jpg",
    summary: "American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary car for Ford.",
    director: "James Mangold",
    cast: ["Matt Damon", "Christian Bale", "Jon Bernthal", "Caitriona Balfe"]
  },
  {
    id: 144,
    title: "Catch Me If You Can",
    year: 2002,
    rating: 8.1,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTY5MzYzNjc5NV5BMl5BanBnXkFtZTYwNTUyNTc2._V1_SX300.jpg",
    summary: "Barely 21 yet, Frank is a skilled forger who has passed as a doctor, lawyer and pilot. FBI agent Carl becomes obsessed with tracking down the con man.",
    director: "Steven Spielberg",
    cast: ["Leonardo DiCaprio", "Tom Hanks", "Christopher Walken", "Martin Sheen"]
  },
  {
    id: 145,
    title: "The Wizard of Oz",
    year: 1939,
    rating: 8.1,
    genre: "Fantasy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNjUyMTc4MDExMV5BMl5BanBnXkFtZTgwNDg0NDIwMjE@._V1_SX300.jpg",
    summary: "Dorothy Gale is swept away from a farm in Kansas to a magical land of Oz in a tornado and embarks on a quest with new friends to see the Wizard.",
    director: "Victor Fleming, George Cukor",
    cast: ["Judy Garland", "Frank Morgan", "Ray Bolger", "Bert Lahr"]
  },
  {
    id: 146,
    title: "12 Years a Slave",
    year: 2013,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjE4MTMzOTc3OF5BMl5BanBnXkFtZTcwMDQzNzMzOQ@@._V1_SX300.jpg",
    summary: "In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.",
    director: "Steve McQueen",
    cast: ["Chiwetel Ejiofor", "Michael Kenneth Williams", "Michael Fassbender", "Brad Pitt"]
  },
  {
    id: 147,
    title: "Barry Lyndon",
    year: 1975,
    rating: 8.1,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNmY0MWY2NDctZDdmMi00MjA1LTk0ZTQtZDMyZTQ1NTNlYzVjXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    director: "Frank Darabont",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"]
  },
  {
    id: 2,
    title: "The Godfather",
    year: 1972,
    rating: 9.2,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton"]
  },
  {
    id: 3,
    title: "The Dark Knight",
    year: 2008,
    rating: 9.0,
    genre: "Action",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    summary: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"]
  },
  {
    id: 4,
    title: "Pulp Fiction",
    year: 1994,
    rating: 8.9,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"]
  },
  {
    id: 5,
    title: "Schindler's List",
    year: 1993,
    rating: 9.0,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.",
    director: "Steven Spielberg",
    cast: ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes", "Caroline Goodall"]
  },
  {
    id: 6,
    title: "Forrest Gump",
    year: 1994,
    rating: 8.8,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    summary: "The presidencies of Kennedy and Johnson unfold through the perspective of an Alabama man with an IQ of 75.",
    director: "Robert Zemeckis",
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"]
  },
  {
    id: 7,
    title: "Inception",
    year: 2010,
    rating: 8.8,
    genre: "Sci-Fi",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    summary: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.",
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"]
  },
  {
    id: 8,
    title: "Fight Club",
    year: 1999,
    rating: 8.8,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    summary: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    director: "David Fincher",
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf"]
  },
  {
    id: 9,
    title: "The Matrix",
    year: 1999,
    rating: 8.7,
    genre: "Sci-Fi",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    director: "Lana Wachowski, Lilly Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"]
  },
  {
    id: 10,
    title: "Goodfellas",
    year: 1990,
    rating: 8.7,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "The story of Henry Hill and his life in the mob, covering his relationship with his wife and his partners in crime.",
    director: "Martin Scorsese",
    cast: ["Robert De Niro", "Ray Liotta", "Joe Pesci", "Lorraine Bracco"]
  },
  {
    id: 11,
    title: "Interstellar",
    year: 2014,
    rating: 8.6,
    genre: "Sci-Fi",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    summary: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"]
  },
  {
    id: 12,
    title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    rating: 9.0,
    genre: "Fantasy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom.",
    director: "Peter Jackson",
    cast: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen", "Orlando Bloom"]
  },
  {
    id: 13,
    title: "Star Wars: Episode V - The Empire Strikes Back",
    year: 1980,
    rating: 8.7,
    genre: "Sci-Fi",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda.",
    director: "Irvin Kershner",
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Billy Dee Williams"]
  },
  {
    id: 14,
    title: "The Silence of the Lambs",
    year: 1991,
    rating: 8.6,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
    director: "Jonathan Demme",
    cast: ["Jodie Foster", "Anthony Hopkins", "Lawrence A. Bonney", "Kasi Lemmons"]
  },
  {
    id: 15,
    title: "Saving Private Ryan",
    year: 1998,
    rating: 8.6,
    genre: "War",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg",
    summary: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed.",
    director: "Steven Spielberg",
    cast: ["Tom Hanks", "Matt Damon", "Tom Sizemore", "Edward Burns"]
  },
  {
    id: 16,
    title: "The Green Mile",
    year: 1999,
    rating: 8.6,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg",
    summary: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
    director: "Frank Darabont",
    cast: ["Tom Hanks", "Michael Clarke Duncan", "David Morse", "Bonnie Hunt"]
  },
  {
    id: 17,
    title: "Parasite",
    year: 2019,
    rating: 8.5,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    summary: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    director: "Bong Joon Ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"]
  },
  {
    id: 18,
    title: "The Lion King",
    year: 1994,
    rating: 8.5,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg",
    summary: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
    director: "Roger Allers, Rob Minkoff",
    cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones", "Moira Kelly"]
  },
  {
    id: 19,
    title: "Gladiator",
    year: 2000,
    rating: 8.5,
    genre: "Action",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    director: "Ridley Scott",
    cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed"]
  },
  {
    id: 20,
    title: "The Departed",
    year: 2006,
    rating: 8.5,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg",
    summary: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
    director: "Martin Scorsese",
    cast: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson", "Mark Wahlberg"]
  },
  {
    id: 21,
    title: "Back to the Future",
    year: 1985,
    rating: 8.5,
    genre: "Sci-Fi",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    summary: "Marty McFly, a teenager, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his friend, Dr. Emmett Brown.",
    director: "Robert Zemeckis",
    cast: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson", "Crispin Glover"]
  },
  {
    id: 22,
    title: "Whiplash",
    year: 2014,
    rating: 8.5,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    summary: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing.",
    director: "Damien Chazelle",
    cast: ["Miles Teller", "J.K. Simmons", "Paul Reiser", "Melissa Benoist"]
  },
  {
    id: 23,
    title: "The Prestige",
    year: 2006,
    rating: 8.5,
    genre: "Mystery",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg",
    summary: "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have.",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Hugh Jackman", "Scarlett Johansson", "Michael Caine"]
  },
  {
    id: 24,
    title: "The Usual Suspects",
    year: 1995,
    rating: 8.5,
    genre: "Mystery",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met by chance.",
    director: "Bryan Singer",
    cast: ["Kevin Spacey", "Gabriel Byrne", "Chazz Palminteri", "Stephen Baldwin"]
  },
  {
    id: 25,
    title: "Spirited Away",
    year: 2001,
    rating: 8.6,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    summary: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
    director: "Hayao Miyazaki",
    cast: ["Daveigh Chase", "Suzanne Pleshette", "Miyu Irino", "Rumi Hiiragi"]
  },
  {
    id: 26,
    title: "American History X",
    year: 1998,
    rating: 8.5,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZTJhN2FkYWEtMGI0My00YWM4LWI2MjAtM2UwNjY4MTI2ZTQyXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_SX300.jpg",
    summary: "A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.",
    director: "Tony Kaye",
    cast: ["Edward Norton", "Edward Furlong", "Beverly D'Angelo", "Avery Brooks"]
  },
  {
    id: 27,
    title: "City of God",
    year: 2002,
    rating: 8.6,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOTMwYjc5ZmItYTFjZC00ZGQ3LTlkNTMtMjZiNTZlMWQzNzI5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
    director: "Fernando Meirelles, Kátia Lund",
    cast: ["Alexandre Rodrigues", "Leandro Firmino", "Matheus Nachtergaele", "Phellipe Haagensen"]
  },
  {
    id: 28,
    title: "Terminator 2: Judgment Day",
    year: 1991,
    rating: 8.6,
    genre: "Action",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son from a more advanced terminator.",
    director: "James Cameron",
    cast: ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong", "Robert Patrick"]
  },
  {
    id: 29,
    title: "Once Upon a Time in the West",
    year: 1968,
    rating: 8.5,
    genre: "Western",
    poster_url: "https://m.media-amazon.com/images/M/MV5BODQ3NDExOGYtMzI3Mi00NWRlLTkwNjAtNjc4MDgzZGJiZTA1XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    summary: "A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin.",
    director: "Sergio Leone",
    cast: ["Henry Fonda", "Charles Bronson", "Claudia Cardinale", "Jason Robards"]
  },
  {
    id: 30,
    title: "Psycho",
    year: 1960,
    rating: 8.5,
    genre: "Horror",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "A Phoenix secretary embezzles money and runs away to a remote motel where she encounters Norman Bates and his domineering mother.",
    director: "Alfred Hitchcock",
    cast: ["Anthony Perkins", "Janet Leigh", "Vera Miles", "John Gavin"]
  },
  {
    id: 31,
    title: "Casablanca",
    year: 1942,
    rating: 8.5,
    genre: "Romance",
    poster_url: "https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg",
    summary: "A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis.",
    director: "Michael Curtiz",
    cast: ["Humphrey Bogart", "Ingrid Bergman", "Paul Henreid", "Claude Rains"]
  },
  {
    id: 32,
    title: "Modern Times",
    year: 1936,
    rating: 8.5,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYjJiZjMzYzktNjU0NS00OTkxLWEwYzItYzdhYWJjN2QzMTRlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "The Tramp struggles to live in modern industrial society with the help of a young homeless woman.",
    director: "Charlie Chaplin",
    cast: ["Charlie Chaplin", "Paulette Goddard", "Henry Bergman", "Tiny Sandford"]
  },
  {
    id: 33,
    title: "City Lights",
    year: 1931,
    rating: 8.5,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BY2I4MmM1N2EtM2YzOS00OWUzLTkzYzctNDc5NDg2N2IyODJmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "With the aid of a wealthy erratic tippler, a dewy-eyed tramp who has fallen in love with a flower girl pursues a cure for her blindness.",
    director: "Charlie Chaplin",
    cast: ["Charlie Chaplin", "Virginia Cherrill", "Florence Lee", "Harry Myers"]
  },
  {
    id: 34,
    title: "Alien",
    year: 1979,
    rating: 8.5,
    genre: "Horror",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NGE5LWEyYmMtOGQ1ZGZjNmRkYjFhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    summary: "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.",
    director: "Ridley Scott",
    cast: ["Sigourney Weaver", "Tom Skerritt", "John Hurt", "Veronica Cartwright"]
  },
  {
    id: 35,
    title: "Apocalypse Now",
    year: 1979,
    rating: 8.4,
    genre: "War",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMDdhODg0MjYtYzBiOS00ZmI5LWEwZGYtZDEyNDU4MmQyNzFjXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.",
    director: "Francis Ford Coppola",
    cast: ["Martin Sheen", "Marlon Brando", "Robert Duvall", "Frederic Forrest"]
  },
  {
    id: 36,
    title: "Django Unchained",
    year: 2012,
    rating: 8.4,
    genre: "Western",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg",
    summary: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner.",
    director: "Quentin Tarantino",
    cast: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio", "Kerry Washington"]
  },
  {
    id: 37,
    title: "Memento",
    year: 2000,
    rating: 8.4,
    genre: "Mystery",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "A man with short-term memory loss attempts to track down his wife's murderer.",
    director: "Christopher Nolan",
    cast: ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano", "Mark Boone Junior"]
  },
  {
    id: 38,
    title: "The Pianist",
    year: 2002,
    rating: 8.5,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
    director: "Roman Polanski",
    cast: ["Adrien Brody", "Thomas Kretschmann", "Frank Finlay", "Emilia Fox"]
  },
  {
    id: 39,
    title: "WALL·E",
    year: 2008,
    rating: 8.4,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_SX300.jpg",
    summary: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will decide the fate of mankind.",
    director: "Andrew Stanton",
    cast: ["Ben Burtt", "Elissa Knight", "Jeff Garlin", "Fred Willard"]
  },
  {
    id: 40,
    title: "The Truman Show",
    year: 1998,
    rating: 8.2,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMDIzODcyY2EtMmY2MC00ZWVlLTgwMzAtMjQwOWUyNmJjNTYyXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
    summary: "A man discovers his entire life is a TV show broadcast to the world.",
    director: "Peter Weir",
    cast: ["Jim Carrey", "Ed Harris", "Laura Linney", "Noah Emmerich"]
  },
  {
    id: 41,
    title: "The Lives of Others",
    year: 2006,
    rating: 8.4,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNmQyNmJjM2ItNTQzYi00ZjMxLWFjMDYtZjUyN2YwZDk5YWQ2XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    summary: "In 1984 East Berlin, an agent of the secret police becomes increasingly absorbed into the lives of a writer and his lover.",
    director: "Florian Henckel von Donnersmarck",
    cast: ["Ulrich Mühe", "Martina Gedeck", "Sebastian Koch", "Ulrich Tukur"]
  },
  {
    id: 42,
    title: "Grave of the Fireflies",
    year: 1988,
    rating: 8.5,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZmY2NjUzNDQtNTgxNC00M2Q4LTljOWQtMjNjNDBjNWUxNmJlXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
    summary: "A young boy and his little sister struggle to survive in Japan during World War II.",
    director: "Isao Takahata",
    cast: ["Tsutomu Tatsumi", "Ayano Shiraishi", "Akemi Yamaguchi", "Yoshiko Shinohara"]
  },
  {
    id: 43,
    title: "Paths of Glory",
    year: 1957,
    rating: 8.4,
    genre: "War",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOTI5Nzc0OTMtYzBkMS00NjkxLThmM2UtNjM2ODgxN2M5NjNkXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg",
    summary: "After refusing to attack an enemy position, a general accuses the soldiers of cowardice and their commanding officer must defend them.",
    director: "Stanley Kubrick",
    cast: ["Kirk Douglas", "Ralph Meeker", "Adolphe Menjou", "George Macready"]
  },
  {
    id: 44,
    title: "The Shining",
    year: 1980,
    rating: 8.4,
    genre: "Horror",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    summary: "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.",
    director: "Stanley Kubrick",
    cast: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd", "Scatman Crothers"]
  },
  {
    id: 45,
    title: "Dr. Strangelove",
    year: 1964,
    rating: 8.4,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "An insane general triggers a path to nuclear holocaust that a war room full of politicians and generals frantically tries to stop.",
    director: "Stanley Kubrick",
    cast: ["Peter Sellers", "George C. Scott", "Sterling Hayden", "Keenan Wynn"]
  },
  {
    id: 46,
    title: "Avengers: Infinity War",
    year: 2018,
    rating: 8.4,
    genre: "Action",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg",
    summary: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos.",
    director: "Anthony Russo, Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo", "Chris Evans"]
  },
  {
    id: 47,
    title: "Witness for the Prosecution",
    year: 1957,
    rating: 8.4,
    genre: "Mystery",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNDQwODU5OWYtNDcyNi00MDQ1LThiOGMtZDkwNWJiM2Y3MDg0XkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg",
    summary: "A veteran British barrister must defend his client in a murder trial that has surprise after surprise.",
    director: "Billy Wilder",
    cast: ["Tyrone Power", "Marlene Dietrich", "Charles Laughton", "Elsa Lanchester"]
  },
  {
    id: 48,
    title: "The Great Dictator",
    year: 1940,
    rating: 8.4,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMmExYWJjNTktNGUyZS00ODhmLTkxYzctYjQwNzA2Y2IwMzNhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.",
    director: "Charlie Chaplin",
    cast: ["Charlie Chaplin", "Paulette Goddard", "Jack Oakie", "Reginald Gardiner"]
  },
  {
    id: 49,
    title: "Aliens",
    year: 1986,
    rating: 8.4,
    genre: "Action",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZGU2OGY5ZTYtMWNhYy00NjZiLWI0NjUtZmNhY2JhNDRmODU3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "Fifty-seven years after surviving an apocalyptic attack aboard her space vessel, Ellen Ripley awakens from hyper-sleep and returns to LV-426.",
    director: "James Cameron",
    cast: ["Sigourney Weaver", "Michael Biehn", "Carrie Henn", "Paul Reiser"]
  },
  {
    id: 50,
    title: "The Dark Knight Rises",
    year: 2012,
    rating: 8.4,
    genre: "Action",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg",
    summary: "Eight years after the Joker's reign of chaos, Batman is coerced out of exile with the assistance of the mysterious Selina Kyle.",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Tom Hardy", "Anne Hathaway", "Gary Oldman"]
  },
  {
    id: 51,
    title: "Oldboy",
    year: 2003,
    rating: 8.4,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTI3NTQyMzU5M15BMl5BanBnXkFtZTcwMTM2MjgyMQ@@._V1_SX300.jpg",
    summary: "After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days.",
    director: "Park Chan-wook",
    cast: ["Choi Min-sik", "Yoo Ji-tae", "Kang Hye-jeong", "Kim Byeong-Ok"]
  },
  {
    id: 52,
    title: "Coco",
    year: 2017,
    rating: 8.4,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_SX300.jpg",
    summary: "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather.",
    director: "Lee Unkrich, Adrian Molina",
    cast: ["Anthony Gonzalez", "Gael García Bernal", "Benjamin Bratt", "Alanna Ubach"]
  },
  {
    id: 53,
    title: "Amadeus",
    year: 1984,
    rating: 8.4,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNWJlNzUzNGMtYTAwMS00ZjI2LWFmNWQtODcxNWUxODA5YmU1XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
    summary: "The life, success and troubles of Wolfgang Amadeus Mozart, as told by Antonio Salieri, the contemporaneous composer who was insanely jealous of Mozart.",
    director: "Miloš Forman",
    cast: ["F. Murray Abraham", "Tom Hulce", "Elizabeth Berridge", "Roy Dotrice"]
  },
  {
    id: 54,
    title: "Toy Story",
    year: 1995,
    rating: 8.3,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_SX300.jpg",
    summary: "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.",
    director: "John Lasseter",
    cast: ["Tom Hanks", "Tim Allen", "Don Rickles", "Jim Varney"]
  },
  {
    id: 55,
    title: "Braveheart",
    year: 1995,
    rating: 8.3,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMzkzMmU0YTYtOWM3My00YzBmLWI0YzctOGYyNTkwMWE5MTJkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.",
    director: "Mel Gibson",
    cast: ["Mel Gibson", "Sophie Marceau", "Patrick McGoohan", "Angus Macfadyen"]
  },
  {
    id: 56,
    title: "Joker",
    year: 2019,
    rating: 8.4,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    summary: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society and embarks on a downward spiral.",
    director: "Todd Phillips",
    cast: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz", "Frances Conroy"]
  },
  {
    id: 57,
    title: "Capernaum",
    year: 2018,
    rating: 8.4,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BY2Y3OWNkMTctYzNjYS00NWVkLTg4OWEtY2YxN2I3NDhlYzdlXkEyXkFqcGdeQXVyMTI3ODAyMzE2._V1_SX300.jpg",
    summary: "While serving a five-year sentence, a 12-year-old boy sues his parents for neglect.",
    director: "Nadine Labaki",
    cast: ["Zain Al Rafeea", "Yordanos Shiferaw", "Boluwatife Treasure Bankole", "Kawsar Al Haddad"]
  },
  {
    id: 58,
    title: "Princess Mononoke",
    year: 1997,
    rating: 8.4,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNGIzY2IzODQtNThmMi00ZDE4LWI5YzAtNzNlZTM1ZjYyYjUyXkEyXkFqcGdeQXVyODEzNjM5OTQ@._V1_SX300.jpg",
    summary: "On a journey to find the cure for a Tatarigami's curse, Ashitaka finds himself in the middle of a war between the forest gods and a mining colony.",
    director: "Hayao Miyazaki",
    cast: ["Yōji Matsuda", "Yuriko Ishida", "Yūko Tanaka", "Billy Crudup"]
  },
  {
    id: 59,
    title: "Spider-Man: Into the Spider-Verse",
    year: 2018,
    rating: 8.4,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_SX300.jpg",
    summary: "Teen Miles Morales becomes Spider-Man of his reality, crossing his path with five counterparts from other dimensions to stop a threat.",
    director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    cast: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld", "Mahershala Ali"]
  },
  {
    id: 60,
    title: "Once Upon a Time in America",
    year: 1984,
    rating: 8.3,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMGFkNWI4MTMtNGQ0OC00MWVmLTk3MTktOGYxN2Y2YWVkZWE2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later for one last job.",
    director: "Sergio Leone",
    cast: ["Robert De Niro", "James Woods", "Elizabeth McGovern", "Joe Pesci"]
  },
  {
    id: 61,
    title: "Your Name",
    year: 2016,
    rating: 8.4,
    genre: "Animation",
    poster_url: "https://m.media-amazon.com/images/M/MV5BODRmZDVmNzUtZDA4ZC00NjhkLWI2M2UtN2M0ZDIzNDcxYThjL2ltYWdlXkEyXkFqcGdeQXVyNTk0MzMzODA@._V1_SX300.jpg",
    summary: "Two strangers find themselves linked in a bizarre way and when a connection forms, will distance be the only thing to keep them apart?",
    director: "Makoto Shinkai",
    cast: ["Ryûnosuke Kamiki", "Mone Kamishiraishi", "Ryô Narita", "Aoi Yûki"]
  },
  {
    id: 62,
    title: "3 Idiots",
    year: 2009,
    rating: 8.4,
    genre: "Comedy",
    poster_url: "https://m.media-amazon.com/images/M/MV5BNTkyOGVjMGEtNmQzZi00NzFlLTlhOWQtODYyMDc2ZGJmYzFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "Two friends are searching for their long lost companion who inspired them to think differently, even as the rest of the world called them idiots.",
    director: "Rajkumar Hirani",
    cast: ["Aamir Khan", "Madhavan", "Mona Singh", "Sharman Joshi"]
  },
  {
    id: 63,
    title: "High and Low",
    year: 1963,
    rating: 8.4,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYWY5ZjhjNGYtZmVjYS00YWQyLWJmM2ItYzM5MTQxNGU0ZDYyXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
    summary: "An executive of a Yokohama shoe company becomes a victim of extortion when his chauffeur's son is kidnapped by mistake.",
    director: "Akira Kurosawa",
    cast: ["Toshirô Mifune", "Tatsuya Nakadai", "Kyôko Kagawa", "Tatsuya Mihashi"]
  },
  {
    id: 64,
    title: "Reservoir Dogs",
    year: 1992,
    rating: 8.3,
    genre: "Crime",
    poster_url: "https://m.media-amazon.com/images/M/MV5BZmExNmEwYWItYmQzOS00YjA5LTk2MjktZjEyZDE1Y2QxNjA1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    summary: "When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.",
    director: "Quentin Tarantino",
    cast: ["Harvey Keitel", "Tim Roth", "Michael Madsen", "Steve Buscemi"]
  },
  {
    id: 65,
    title: "2001: A Space Odyssey",
    year: 1968,
    rating: 8.3,
    genre: "Sci-Fi",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMmNlYzRiNDctZWNhMi00MzI4LThkZTctMTUzMmZkMmFmNThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "After discovering a mysterious artifact buried beneath the Lunar surface, mankind sets off on a quest to find its origins with HAL 9000.",
    director: "Stanley Kubrick",
    cast: ["Keir Dullea", "Gary Lockwood", "William Sylvester", "Douglas Rain"]
  },
  {
    id: 66,
    title: "Requiem for a Dream",
    year: 2000,
    rating: 8.3,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BOTdiNzJlOWUtNWMwNS00NmFlLWI0YTEtZmI3YjIzZWUyY2Y3XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    summary: "The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.",
    director: "Darren Aronofsky",
    cast: ["Ellen Burstyn", "Jared Leto", "Jennifer Connelly", "Marlon Wayans"]
  },
  {
    id: 67,
    title: "Eternal Sunshine of the Spotless Mind",
    year: 2004,
    rating: 8.3,
    genre: "Romance",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX300.jpg",
    summary: "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.",
    director: "Michel Gondry",
    cast: ["Jim Carrey", "Kate Winslet", "Tom Wilkinson", "Gerry Robert Byrne"]
  },
  {
    id: 68,
    title: "Lawrence of Arabia",
    year: 1962,
    rating: 8.3,
    genre: "Adventure",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYWY5ZjhjNGYtZmI2Ny00ODM0LWFkNzgtZmI1YzA2N2MxMzA0XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg",
    summary: "The story of T.E. Lawrence, the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I.",
    director: "David Lean",
    cast: ["Peter O'Toole", "Alec Guinness", "Anthony Quinn", "Jack Hawkins"]
  },
  {
    id: 69,
    title: "Citizen Kane",
    year: 1941,
    rating: 8.3,
    genre: "Drama",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYjBiOTYxZWItMzdiZi00NjlkLWIzZTYtYmFhZjhiMTljOTdkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    summary: "Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance: 'Rosebud'.",
    director: "Orson Welles",
    cast: ["Orson Welles", "Joseph Cotten", "Dorothy Comingore", "Agnes Moorehead"]
  },
  {
    id: 70,
    title: "M",
    year: 1931,
    rating: 8.3,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BODA4ODk3OTEzMF5BMl5BanBnXkFtZTgwMTQ2ODMwMzE@._V1_SX300.jpg",
    summary: "When the police in a German city are unable to catch a child-murderer, other criminals join in the manhunt.",
    director: "Fritz Lang",
    cast: ["Peter Lorre", "Ellen Widmann", "Inge Landgut", "Otto Wernicke"]
  },
  {
    id: 71,
    title: "Vertigo",
    year: 1958,
    rating: 8.3,
    genre: "Mystery",
    poster_url: "https://m.media-amazon.com/images/M/MV5BYTE4ODEwZDUtNDFjOC00NjAxLWEzYTQtYTI1NGVmZmFlNjdiL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
    summary: "A former police detective juggles wrestling with his personal demons and becoming obsessed with a beautiful woman seemingly possessed.",
    director: "Alfred Hitchcock",
    cast: ["James Stewart", "Kim Novak", "Barbara Bel Geddes", "Tom Helmore"]
  },
  {
    id: 72,
    title: "Double Indemnity",
    year: 1944,
    rating: 8.3,
    genre: "Thriller",
    poster_url: "https://m.media-amazon.com/images/M/MV5BMGMwZTIxYTEtMTY4ZS00ZTIwLTljNmQtNzgzMWQ2ZTFlOTU5XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
    summary: "An insurance representative lets himself be talked by a seductive housewife into a murder/insurance fraud scheme that arouses suspicion.",
    director: "Billy Wilder",
    cast: ["Fred MacMurray", "Barbara Stanwyck", "Edward G. Robinson", "Byron Barr"]
  },
    ];
